### ISSUE TITLE
need a build card function

### ISSUE THREAD

**Issue by IzetopeDev** [FelixIsaac/kopi-cats#8]
we should add a build card function in such that in app.py everything will be more readable later in the future. 
by the way should we make it in a separate file for all the cards? not exactly sure how it function

**Comment by FelixIsaac** [comment]
@icesotope41, in commit https://github.com/FelixIsaac/kopi-cats/commit/41c8bf4bfd8c7f7a4ccdc82be16d94312b3093f0. There is already a build function for the `Card` class, so I was thinking that we since we are already inheriting the `Card` class, we are able to add the `build` function to every card class and build by calling the build function.

**Comment by IzetopeDev** [comment]
I didn't mean that "build card" tbh idk what the function name should be. we need a function to make the card "sprites" appear on screen which is not directly coded into the main loop. So basically somewhat like function oriented programming. (though i'm not super sure what function oriented programming shd be lol) i'll try to clarify in person or on call if possible.
